<?php
namespace App\Http\Controllers\Crm;
use App\Http\Controllers\Controller;use App\Models\{Branch,Customer};use App\Services\CustomerDedupService;use Illuminate\Http\Request;
class CustomerController extends Controller {public function __construct(private CustomerDedupService $dedup){}
 public function index(Request $r){$u=$r->user();$cs=Customer::with(['contacts','branch'])->when(!$u->isCeo(),fn($q)=>$q->where('branch_id',$u->branch_id))->when($r->filled('q'),fn($q)=>$q->where(fn($x)=>$x->where('name','like','%'.$r->q.'%')->orWhereHas('contacts',fn($c)=>$c->where('value','like','%'.$r->q.'%'))))->latest()->paginate(20)->withQueryString();return view('crm.customers.index',compact('cs'));}
 public function create(Request $r){$branches=Branch::all();$duplicates=collect($r->session()->pull('dedup_preview',[]));return view('crm.customers.create',compact('branches','duplicates'));}
 public function store(Request $r){$d=$r->validate(['name'=>'required|string|max:100','address'=>'nullable|string|max:255','source'=>'nullable|string|max:50','branch_id'=>'required|exists:branches,id','notes'=>'nullable|string','contact_type'=>'required|array|min:1','contact_type.*'=>'in:phone,whatsapp,email,other','contact_value'=>'required|array|min:1','contact_value.*'=>'required|string|max:150','contact_primary'=>'nullable|integer','confirm_create'=>'nullable|boolean']);if(!$r->user()->isCeo())$d['branch_id']=$r->user()->branch_id;$phone=null;foreach($d['contact_type'] as $i=>$t)if(in_array($t,['phone','whatsapp'],true)){$phone=$d['contact_value'][$i];break;}if(empty($d['confirm_create'])&&($du=$this->dedup->findPossibleDuplicates($d['name'],$phone,$d['address']??null))->isNotEmpty())return back()->withInput()->with('dedup_preview',$du->map(fn($x)=>['id'=>$x['customer']->id,'name'=>$x['customer']->name,'reason'=>$x['reason']])->all());$contacts=[];foreach($d['contact_type'] as $i=>$t)$contacts[]=['type'=>$t,'value'=>$d['contact_value'][$i],'is_primary'=>(int)($d['contact_primary']??0)===$i];if(!collect($contacts)->contains('is_primary',true))$contacts[0]['is_primary']=true;$c=Customer::register(collect($d)->only(['name','address','source','branch_id','notes'])->all(),$contacts,$r->user());return redirect()->route('crm.customers.show',$c)->with('ok','Pelanggan berhasil didaftarkan.');}
 private function authorizeBranch(Request $r,Customer $customer):void{abort_unless($r->user()->isCeo()||$customer->branch_id===$r->user()->branch_id,403);}
 public function show(Request $r,Customer $customer){$this->authorizeBranch($r,$customer);$customer->load(['contacts','branch','creator','purchases.items','reminders','histories.user']);return view('crm.customers.show',compact('customer'));}
 public function edit(Request $r,Customer $customer){$this->authorizeBranch($r,$customer);$branches=Branch::all();return view('crm.customers.edit',compact('customer','branches'));}
 public function update(Request $r,Customer $customer){$this->authorizeBranch($r,$customer);$d=$r->validate(['name'=>'required|string|max:100','address'=>'nullable|string|max:255','source'=>'nullable|string|max:50','branch_id'=>'required|exists:branches,id','notes'=>'nullable|string']);if(!$r->user()->isCeo())$d['branch_id']=$customer->branch_id;$customer->updateInfo($d,$r->user());return redirect()->route('crm.customers.show',$customer)->with('ok','Data pelanggan diperbarui.');}
 public function destroy(Request $r,Customer $customer){$this->authorizeBranch($r,$customer);$customer->histories()->create(['user_id'=>$r->user()->id,'action'=>'deleted','created_at'=>now()]);$customer->delete();return redirect()->route('crm.customers.index')->with('ok','Pelanggan dihapus.');}}
