@extends('layouts.app')
@section('title', 'Detail Penjualan')
@section('content')
<div class="mx-auto max-w-5xl space-y-5">
    <div class="flex flex-wrap items-start justify-between gap-3"><div><a href="{{ route('crm.sales.index') }}" class="text-sm text-emerald-700">← Penjualan</a><h1 class="mt-1 text-2xl font-bold">Penjualan #{{ $purchase->id }}</h1><p class="text-sm text-slate-500">{{ $purchase->purchased_at->format('d M Y') }} · {{ $purchase->branch->name }}</p></div>
        @if(auth()->user()->isCeo())<div class="flex gap-2"><a href="{{ route('crm.sales.edit', $purchase) }}" class="rounded-lg border px-4 py-2 font-semibold">Edit</a><form method="POST" action="{{ route('crm.sales.destroy', $purchase) }}" onsubmit="return confirm('Hapus transaksi ini? Data akan hilang dari laporan penjualan.')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-200 px-4 py-2 font-semibold text-rose-600">Hapus</button></form></div>@endif
    </div>
    <div class="grid gap-5 md:grid-cols-3">
        <div class="rounded-xl border bg-white p-5"><p class="text-xs uppercase text-slate-400">Pelanggan</p><a href="{{ route('crm.customers.show', $purchase->customer) }}" class="mt-1 block text-lg font-bold text-emerald-700">{{ $purchase->customer->name }}</a>@foreach($purchase->customer->contacts->whereIn('type', ['phone','whatsapp']) as $contact)<p class="text-sm text-slate-600">{{ $contact->value }}</p>@endforeach<p class="mt-3 text-xs text-slate-400">Sumber</p><p>{{ $purchase->customer->source ?: '—' }}</p><p class="mt-3 text-xs text-slate-400">Domisili</p><p>{{ $purchase->customer->address ?: '—' }}</p></div>
        <div class="md:col-span-2 overflow-hidden rounded-xl border bg-white"><table class="w-full text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-3 text-left">Produk</th><th class="p-3 text-left">Brand / tipe</th><th class="p-3 text-center">Qty</th><th class="p-3 text-right">Harga</th><th class="p-3 text-right">Subtotal</th></tr></thead><tbody class="divide-y">@foreach($purchase->items as $item)<tr><td class="p-3 font-semibold">{{ $item->product_name }}</td><td class="p-3 text-slate-500">{{ collect([$item->brand, $item->product_type])->filter()->join(' · ') ?: '—' }}</td><td class="p-3 text-center">{{ $item->quantity }}</td><td class="p-3 text-right">Rp {{ number_format($item->unit_price, 0, ',', '.') }}</td><td class="p-3 text-right font-semibold">Rp {{ number_format($item->subtotal, 0, ',', '.') }}</td></tr>@endforeach</tbody><tfoot class="border-t-2"><tr><td colspan="4" class="p-3 text-right font-bold">Total</td><td class="p-3 text-right text-lg font-bold text-emerald-700">Rp {{ number_format($purchase->total_amount, 0, ',', '.') }}</td></tr></tfoot></table></div>
    </div>
    <div class="grid gap-5 md:grid-cols-2"><div class="rounded-xl border bg-white p-5"><h2 class="font-bold">Informasi transaksi</h2><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-xs text-slate-400">Pembayaran</dt><dd>{{ \App\Models\Purchase::PAYMENT_METHODS[$purchase->payment_method] ?? $purchase->payment_method }}</dd></div><div><dt class="text-xs text-slate-400">Dicatat oleh</dt><dd>{{ $purchase->creator->name }}</dd></div><div class="col-span-2"><dt class="text-xs text-slate-400">Catatan</dt><dd>{{ $purchase->notes ?: '—' }}</dd></div></dl></div>
        <div class="rounded-xl border bg-white p-5"><h2 class="font-bold">Jadwal follow-up</h2><div class="mt-3 space-y-2">@foreach($purchase->reminders->sortBy('scheduled_at') as $reminder)<div class="flex items-center justify-between text-sm"><span>{{ \App\Models\Reminder::TYPES[$reminder->type] ?? $reminder->type }}</span><span class="{{ $reminder->status === 'completed' ? 'text-emerald-600' : 'text-slate-500' }}">{{ $reminder->scheduled_at->format('d M Y') }} · {{ \App\Models\Reminder::STATUSES[$reminder->status] }}</span></div>@endforeach</div></div>
    </div>
</div>
@endsection
